repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        files: '\.(cpp|hpp|c|h)$'
      - id: clang-tidy
        files: '\.(cpp|hpp|c|h)$'
        args: ['-p=build']
