name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            compiler: msvc
            toolset: v143
          - os: ubuntu-latest
            compiler: clang
            version: 16
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14 clang-16 \
            libx11-dev libxi-dev libxrandr-dev libxinerama-dev \
            libxcursor-dev libxext-dev \
            libgl1-mesa-dev libglu1-mesa-dev
          python -m pip install cmake==3.29.2
      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release
      - name: Test
        run: ctest --test-dir build --output-on-failure -C Release
